# Generated by Django 4.0.4 on 2022-04-28 18:36

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to=pages.models.image_directory_path)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('text', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('order', models.IntegerField(blank=True)),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.page')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('text', ckeditor.fields.RichTextField()),
                ('font', models.TextField(max_length=100)),
                ('font_size', models.TextField(max_length=100)),
                ('font_weight', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Social_Media_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('order', models.IntegerField(blank=True)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.image')),
                ('link_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.link')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.project')),
            ],
        ),
        migrations.CreateModel(
            name='Section_Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.section')),
                ('text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.text')),
            ],
        ),
        migrations.CreateModel(
            name='Section_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True)),
                ('link_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.link')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.section')),
            ],
        ),
        migrations.CreateModel(
            name='Section_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True)),
                ('is_background', models.BooleanField(default=False)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.image')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.section')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.project_type'),
        ),
        migrations.AddField(
            model_name='project',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.project'),
        ),
        migrations.CreateModel(
            name='Logo_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.image')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.project')),
            ],
        ),
    ]
