# Generated by Django 4.0.4 on 2022-06-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='defalt',
            field=models.BooleanField(default=False),
        ),
    ]
