# Generated by Django 4.0.4 on 2022-06-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_project_defalt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='defalt',
            new_name='home',
        ),
    ]
