# Generated by Django 4.0.4 on 2022-06-24 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_defalt_project_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user_id',
        ),
    ]
